### ISSUE TITLE
Don't run dbus-launch if XDG_RUNTIME_DIR/bus is available

### ISSUE THREAD

**Issue by glondu** [ocaml-community/obus#21]
This is a wishlist forwarded from https://bugs.debian.org/836118 :

The major D-Bus implementations (libdbus, GDBus, sd-bus) now have a fallback code path, before trying X11 autolaunch, when DBUS_SESSION_BUS_ADDRESS is unset: if XDG_RUNTIME_DIR
is set, and XDG_RUNTIME_DIR/bus exists, is a socket and is owned by the process's uid, then they will use it. In particular, dbus-user-session sets up that situation.

It would be nice if obus implemented this fallback as well.

**Comment by Freyr666** [comment]
Well, it shouldn't be hard to implement this one, I'll check this out.

**Comment by Freyr666** [comment]
Ok, could you test [a branch](https://github.com/ocaml-community/obus/tree/xdg_fallback), if it works as expected?

**Comment by pmetzger** [comment]
@Freyr666 @glondu if it works as expected, we can merge #22

**Comment by glondu** [comment]
> Ok @glondu, could you test a branch, if it works as expected?

Yes. Thank you for your quick reply!
