### ISSUE TITLE
GPLed program using OBus

### ISSUE THREAD

**Issue by NIR-Ginko** [ocaml-community/obus#24]
I want to implement D-Bus service (daemon) using OBus but my manager demands code to be GPLv2+ licensed and OBus is MIT-licensed. Is it possible to write GPLed software using OBus?

P. S.: It would be nice if you point me to example of service implementation.

**Comment by Freyr666** [comment]
Sorry for late reply.
OBus is BSD 3-clause, afaik it's compatible with GPLv2 [1], but I'm not an expert.

As for examples, yeah, we need a more thorough example, I'll add it to v2 goals. OBus is pretty straightforward D-Bus implementation though.

A (very basic) example of a dbus service is a [simple pong service](https://github.com/ocaml-community/obus/blob/master/examples/pong.ml) in the `examples` directory. There is also a client there called pong. You need to describe an interface in XML, then use `obus-gen-interface` to generate a corresponding ocaml interface. Then register D-Bus objects as it is done in pong.

[1] https://www.gnu.org/licenses/license-list.en.html
